#!/bin/sh
# Thin wrapper: delegates to the stoandl fat JAR in ctl mode.
exec java \
  --add-opens=org.freedesktop.dbus/org.freedesktop.dbus.connections.base=ALL-UNNAMED \
  --add-opens=org.freedesktop.dbus/org.freedesktop.dbus.connections.transports=ALL-UNNAMED \
  -jar /usr/lib/stoandl/stoandl.jar ctl "$@"
